ibis-project/ibis-substrait

- ibis_substrait/compiler/core.py
Removes the one call to `materialize` to maintain compatibility with upstream
> refactor: remove materialize

- poetry.lock
- pyproject.toml
discovered that you can't use the compiler unless we've also installed `protobuf` (which, you know, makes sense)
> chore: add protobuf dependency

- .github/workflows/ci.yml
- ibis_substrait/compiler/core.py
- ibis_substrait/compiler/decompile.py
- ibis_substrait/compiler/mapping.py
- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_compiler.py
- ibis_substrait/tests/compiler/test_decompiler.py
- ibis_substrait/tests/compiler/test_literal.py
- ibis_substrait/tests/compiler/test_tpch.py
- poetry.lock
- pyproject.toml
- shell.nix
`ops.Alias` was added in Ibis recently and the dispatcher was defaulting
to `ops.ValueOp` when it received one -- instead this added in a
specific Alias dispatch rule to pull out the underlying op.
xref ibis-project/ibis#3276
> fix: dispatch underlying op for aliases

- ibis_substrait/compiler/mapping.py
- ibis_substrait/compiler/translate.py
According to the spec, you cannot have the function option argument
specified after a "regular" argument.
Definitely time to add the validator to our CI runs
> fix(extract): substrait function argument ordering

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_literal.py
We need to specify nullability in all literals -- I'm not sure if just defaulting to "YES" is the right move here, but that's definitely my starting point.
> fix: translate all literals as nullable

- ibis_substrait/compiler/translate.py
- poetry.lock
- pyproject.toml
- shell.nix
This PR adds support for ibis-framework 3.1.0 by way of a bit of backcompat
code to `root_tables` when computing join children.
> fix: add support for ibis-framework 3.1.0

- ibis_substrait/compiler/decompile.py
- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_compiler.py
Also add required support for `substrait.algebra_pb2.FunctionArgument`
which is the protobuf message type required for arguments to
`ScalarFunction` and `AggregateFunction`
> refactor: replace deprecated `args` with `arguments`

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_compiler.py
Follow up to #289 -- missed one specification of `FunctionArgument`
> fix(translate): use FunctionArgument in ops.Count translation

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_decompiler.py
- ibis_substrait/tests/compiler/test_tpch.py
The confusion for me has been the location of the `field` lookup,
referenced in the
`expression->scalar_function->arguments->value->selection->direct_reference->struct_field`
Where is the list of columns that pokes in to?
It doesn't explicitly exist -- it is the flattened list of all columns
from the
left and the right tables.
We were correctly calculating the `relative_offset` -- the offset within the
left- or right-table -- but our `base_offset` was wrong.  Why?
Because in some situations, we don't have the `child_rel_field_offsets`
to pass to the `translate` call for the _join predicates_ and they need
to be there.
So we check if that has been calculated, and if it hasn't, then we
calculate them and pass them in.
Also, I am _sure_ there are edge cases that this doesn't cover, but this …
> fix: always calculate child rel field offsets for join predicates

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_decompiler.py
- poetry.lock
- pyproject.toml
I _think_ this is the right fix for the failure to handle nested joins.
The decompiled expression isn't identical, but it I believe it is
equivalent.
I think this fixes #317 
The tests are failing because we're comparing the round-tripped expressions and they aren't identical.
Need to think about how to run those checks.
> fix(joins): compute field offsets for nested joins

- ibis_substrait/compiler/mapping.py
- poetry-overrides.nix
For small differences between releases in 3.x, we ignore missing ops when we generate the inverse mapping.  This has no impact on compilation, only on decompilation, which isn't robust anyway.
Fixes #385
> fix(3.x): ignore missing ops when generating inverse mapping

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_compiler.py
I based this off of the output for similar queries generated by `isthmus`, the `substrait-java` implementation.
I need to figure out how to test this for correctness.
Fixes #365
> fix(projection): Use emit and not project for column selection

- ibis_substrait/compiler/translate.py
This change relaxes the check for source tables to allow any subclass of `PhysicalTable` that has a `.schema` attribute. While this isn't ideal in the long run, it's not terrible and is easy to do for now.
(Hopefully) fixes #393.
> feat: allow source tables other than `UnboundTable`

- poetry.lock
- pyproject.toml
Relax the upper bound for Python. I had to work around ibis-framework 3.x still including the upper bound, but that hack can be removed when we release ibis-framework@4.
> fix(python): relax python upper bound

- ibis_substrait/compiler/mapping.py
- ibis_substrait/compiler/translate.py
if `base` isn't specified we default to the value of `e`
Resolves #407
> feat: add support for ops.Log

- .github/workflows/ci.yml
No reason to run the macos tests twice since we are already running them in the nix job set.
> ci: remove macos poetry job

- .github/workflows/ci.yml
- ibis_substrait/compiler/core.py
- ibis_substrait/compiler/decompile.py
- ibis_substrait/compiler/mapping.py
- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_decompiler.py
- nix/sources.json
- poetry.lock
- pyproject.toml
- shell.nix
A lot of this is semi-gross hacks, but they should be relatively easy to unwind when we drop support for Ibis 3.x (whenever that happens).
Changes:
The biggest hurdle is that we no longer have the expr -> op -> expr ... pattern, it's just ops all the way down.
To maintain compatibility, any reference to something like `op.arg` is now written as `op.arg.op().to_expr()` -- this is gross, but functional. It's a very little bit of extra work, but it makes sure that we get the same object no matter the Ibis version.
Also, because now we're often passing around ops instead of exprs, or because the expr isn't strictly necessary for a bunch of dispatch rules, both `expr` and `compiler` are both keyword arguments now.
Besides that there are some minor shenigans to handle the nonexistence of …
> feat: add initial support for ibis 4.x

- ibis_substrait/compiler/translate.py
- pyproject.toml
This code was a bit spaghetti and hard to follow, especially with the extra branching for multiple versions of Ibis.  Cleaning it up a little bit to make it easier to follow.
> refactor: clean up output mapping in ops.Selection dispatch

- ibis_substrait/compiler/mapping.py
Add ibis -> substrait op mappings for approximation ops
> feat: adding substrait mappings for ibis approx ops

- .github/workflows/ci.yml
I did not think that auto-merge would go through if several CI jobs failed, but you learn something every day.
> chore(poetry): constrain poetry to fix upstream issue

- .github/workflows/ci.yml
- ibis_substrait/tests/compiler/test_compiler.py
- pyproject.toml
Separates the Ibis 3.x and Ibis 4.x into separate jobs, because we can't support the same matrix of Python versions in both.
For both 3.x and 4.x, we want to run on the lowest and highest support versions of Python.
For the `nix` job, we run on all supported versions with ibis 4 to generate the files for cachix.
> chore(ci): separate ibis jobs, only run on lowest and highest supported

- ibis_substrait/compiler/mapping.py
Resolves #493 
There isn't much to test here, but I can add a specific test for the `round` scalar func extension in #510 once this is merged in.
> feat(round): add ops mapping for `round` scalar func

- .gitattributes
- gen-protos.sh
- ibis_substrait/compiler/core.py
- ibis_substrait/compiler/mapping.py
- ibis_substrait/compiler/translate.py
- ibis_substrait/extensions/extension_types.yaml
- ibis_substrait/extensions/functions_aggregate_approx.yaml
- ibis_substrait/extensions/functions_aggregate_generic.yaml
- ibis_substrait/extensions/functions_arithmetic.yaml
- ibis_substrait/extensions/functions_arithmetic_decimal.yaml
- ibis_substrait/extensions/functions_boolean.yaml
- ibis_substrait/extensions/functions_comparison.yaml
- ibis_substrait/extensions/functions_datetime.yaml
- ibis_substrait/extensions/functions_logarithmic.yaml
- ibis_substrait/extensions/functions_rounding.yaml
- ibis_substrait/extensions/functions_set.yaml
- ibis_substrait/extensions/functions_string.yaml
- ibis_substrait/extensions/type_variations.yaml
- ibis_substrait/extensions/unknown.yaml
- ibis_substrait/tests/compiler/test_compiler.py
- ibis_substrait/tests/compiler/test_extensions.py
- ibis_substrait/tests/compiler/test_tpch.py
- poetry.lock
- pyproject.toml
Ok, this is take 2 on adding in proper extension support.
Substrait wants scalar function calls to list a URI that points to a YAML file that defines the name of the scalar function, as well as any options it can take, and also which types are valid inputs.
This turns out to be a bit of a pain to handle automatically -- the function `add`, for instance, is defined in two separate YAML files, one that specifies behavior for ints and floats, the other for decimals.
So here, we add in a `register` function that parses a substrait `YAML` extension file and builds up a mapping of the form:
`map[function name][('tuple', 'of', 'input', 'types')]`
and the value associated with that entry is an object that has the options, URI, etc, associated with that particular function call.
To add to the fun, …
> feat(extensions): add extension URIs to plans

- .github/workflows/ci.yml
- ibis_substrait/compiler/core.py
- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_compiler.py
- ibis_substrait/tests/compiler/test_extensions.py
- ibis_substrait/tests/integration/test_pyarrow.py
- poetry.lock
- pyproject.toml
What does this do?
Adds a dispatch rule for the `ElementWiseVectorizedUDF` op.
This dispatch does the following:
- Uses the ibis type annotations from the UDF decorator to set the expected input and output types of the scalar function.
- sets the URI for this extension (since it is an extension) to the value of the `udf_uri` attribute of the `SubstraitCompiler`.  This should be set at instantiation time.  If there is no available `udf_uri` on the compiler it will error out.
- Returns the substrait scalar function call 
This assumes that you have some other means of registering the UDFs with your execution engine -- there's an example of what that might look like in `ibis_substrait/tests/integrations/tests/test_pyarrow.py`
> feat(udf): add initial support for UDFs

- poetry.lock
- pyproject.toml
We aren't using it explicitly, so it shouldn't need to be included for
end-users.  We DO need it as a `test` dep so that we can filter/suppress
upstream warnings in the test suite.
> chore(poetry): make sqlalchemy a test dependency only

- ibis_substrait/compiler/core.py
- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/test_compiler.py
- ibis_substrait/tests/compiler/test_literal.py
This removes all usage of `expr` being passed explicitly to mapping
functions.  There are a few cases where Ibis 3.x will pass in
expressions still, but those should be handled by the `_expr` rule,
which forwards on the `op` (at a cost of an extra dispatch).
There are also a few bits where we do reductions on predicates that
operate on expressions.  Those should be converted to ops where
possible (without breaking support for older Ibis versions).
> refactor: remove expr arguments in translate

- .github/workflows/ci.yml
- flake.nix
- ibis_substrait/compiler/core.py
- ibis_substrait/compiler/decompile.py
- ibis_substrait/compiler/mapping.py
- ibis_substrait/compiler/translate.py
- nix/overlay.nix
- poetry.lock
- pyproject.toml
In accordance with NEP-29 https://numpy.org/neps/nep-0029-deprecation_policy.html
> refactor: drop support for Python 3.8

- ibis_substrait/compiler/core.py
- ibis_substrait/compiler/mapping.py
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h01/tpc_h01.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h03/tpc_h03.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h04/tpc_h04.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h05/tpc_h05.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h06/tpc_h06.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h090/tpc_h090.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h091/tpc_h091.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h10/tpc_h10.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h11/tpc_h11.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h12/tpc_h12.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h13/tpc_h13.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h18/tpc_h18.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h19/tpc_h19.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h20/tpc_h20.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h21/tpc_h21.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h22/tpc_h22.json
- ibis_substrait/tests/compiler/test_extensions.py
As per a recent change in the spec upstream (and also to enable better
compatibility with other substrait libraries), extension function names
now have the expected input types included in the name of the function.
This can seem very weird, but helps to make it much easier for consumers
to parse a plan.
Basically, if you call a scalar function `add` and pass in two integer
32s, the "name" of the function will be `add:i32_i32`.
We do not validate that the particular signature exists in the
extension.yaml files, but we do perform the requisite upcasting to make
sure that only integers and floats of the same precision are passed to
functions (also in line with the Substrait specification).
Resolves #703
> feat: add type signature to scalar function name definitions

- ibis_substrait/compiler/core.py
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h03/tpc_h03.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h04/tpc_h04.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h05/tpc_h05.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h06/tpc_h06.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h090/tpc_h090.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h091/tpc_h091.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h10/tpc_h10.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h12/tpc_h12.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h13/tpc_h13.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h19/tpc_h19.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h20/tpc_h20.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h21/tpc_h21.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h22/tpc_h22.json
- ibis_substrait/tests/compiler/test_extensions.py
This fixes a bug that I missed when I reintroduced the compound function
signatures.
If we call `add` using int32 and float32, respectively, then we should
have two separate scalar function anchors, one that is `add:i32_i32` and
another that is `add:fp32_fp32`.  This is now handled correctly.
There is a bit of uncertainty about how we handle the signatures for
variadic functions, especially ones that accept (optionally) zero
arguments.
What I have here is my best guess as to the right way to do it, and I
can update it after consulting with the Substrait community at the next meeting.
> fix(extensions): use compound signature when creating new URI

- pyproject.toml
I don't think this is required anymore and it's breaking the nix builds in CI
> chore(tests): remove filter for sqlalchemy warning message

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h01/tpc_h01.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h03/tpc_h03.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h06/tpc_h06.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h091/tpc_h091.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h092/tpc_h092.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h10/tpc_h10.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h18/tpc_h18.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h19/tpc_h19.json
- ibis_substrait/tests/compiler/test_compiler.py
Also updated our selection routine to properly handle the flattened index count for projecting out of these groupbys.
Fixes #878
> fix(grouping): collect multiple grouping keys in single "groupings"

- CONTRIBUTING.md
The instructions for updating the bundled protobuf are defunct, since that is
now handled upstream in `substrait-python` (`substrait` on PyPI).
I also added a section explaining the conventional commits workflow.
> docs: remove defunct proto instructions, add commit guide

- ibis_substrait/compiler/core.py
- ibis_substrait/tests/compiler/test_extensions.py
- nix/checks.nix
- poetry.lock
- pyproject.toml
- chore(pre-commit): switch formatting from black to ruff
- chore(cleanup): remove defunct SubstraitDecompiler class
- test(mapping): confirm sources and targets exist for ops mapping
> chore(cleanup): small fixups before 4.x release

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h08/tpc_h08.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h09/tpc_h09.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h21/tpc_h21.json
- ibis_substrait/tests/compiler/test_compiler.py
JoinChains provide the schema of the joined table (which is great for Ibis)
but for substrait we need the Field index computed with respect to
the original table schemata.  In practice, this means rolling through
the tables in a JoinChain and computing the field index _without_
removing the join key
Given
```
Table 1
a: int
b: int
Table 2
a: int
c: int
JoinChain[r0]
JoinLink[inner, r1]
r0.a == r1.a
values:
a: r0.a
b: r0.b
c: r1.c
```
If we ask for the field index of `c`, the JoinChain schema will give
us an index of `2`, but it should be `3` because
```
0: table 1 a
1: table 1 b
2: table 2 a
3: table 2 c
```
So now we pull out the correct JoinReference object and use that to
index into the tables in the JoinChain and offset by the length of the
schema of those preceding tables.
Resolves …
> fix(field_index): get field index w.r.t. pre-join table schemata

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/parity_utils.py
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h02/tpc_h02.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h03/tpc_h03.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h05/tpc_h05.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h08/tpc_h08.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h09/tpc_h09.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h10/tpc_h10.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h11/tpc_h11.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h12/tpc_h12.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h13/tpc_h13.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h14/tpc_h14.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h15/tpc_h15.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h16/tpc_h16.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h17/tpc_h17.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h18/tpc_h18.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h19/tpc_h19.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h20/tpc_h20.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h21/tpc_h21.json
- ibis_substrait/tests/compiler/test_parity.py
Ibis IR has a bit of a quirky behavior around projections, namely one can define projections both in `ops.Project` object and also as part of `ops.JoinChain`, not sure why that's the case. Current compiler handles only projections defined in `ops.Project`, therefore any selects written after a join chain are ignored.
The PR fixes the issue by injecting a projection node after every join chain in the plan. Technically this is not always necessary, because if the values contained in the `ops.JoinChain` do only column renames and reorders (no new expressions) then substrait's Emit message inside JoinRel can be used as well, but that would require inspecting all values first to make sure that nothing other than field references are present in there.
> fix: handle projections after join chain

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h01/tpc_h01.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h02/tpc_h02.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h03/tpc_h03.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h04/tpc_h04.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h05/tpc_h05.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h06/tpc_h06.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h08/tpc_h08.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h09/tpc_h09.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h10/tpc_h10.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h11/tpc_h11.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h12/tpc_h12.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h13/tpc_h13.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h14/tpc_h14.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h15/tpc_h15.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h16/tpc_h16.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h17/tpc_h17.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h18/tpc_h18.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h19/tpc_h19.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h20/tpc_h20.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h21/tpc_h21.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h22/tpc_h22.json
- ibis_substrait/tests/compiler/test_compiler.py
This is first PR to solve #1145 and adds outputNames hint to all Rels except for JoinRel and CrossRel. Join relations need more work to handle name collisions as ibis doesn't do it for every join step as part of JoinChain.
> feat: add outputNames hint to all Rels except joins

- ibis_substrait/compiler/translate.py
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h08/tpc_h08.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h09/tpc_h09.json
- ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h21/tpc_h21.json
- ibis_substrait/tests/compiler/test_compiler.py
Fixes #1190
Reverts #1078 as the fix is no longer relevant after #1119
> fix: remove unnecessary field index calculation for JoinChain fields
