ibis-project/ibis-substrait

nix/sources.json, poetry-overrides.nix, poetry.lock
- chore(poetry2nix): update
- chore: fix poetry-overrides
- chore(nixpkgs): update
=> chore: fix poetry-overrides and bump poetry2nix and nixpkgs

ibis_substrait/compiler/decompile.py, ibis_substrait/compiler/translate.py
This PR fixes field offset construction.
Currently the child relation is shoehorned in as an utter hack: the child is
treated a struct from which other fields are computed.
Here, we treat all columns from a join as a single flat schema and then track the offsets
throughout compilation and decompilation such that the schema can be reconstructed.
=> fix: fix broken field offset calculation

ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_compiler.py
See https://github.com/ibis-project/ibis-substrait/issues/184
=> feat(compiler): expand table expression to its columns

.envrc, ibis_substrait/compiler/decompile.py, ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_compiler.py, ibis_substrait/tests/compiler/test_decompiler.py, poetry.lock, pyproject.toml
- test: add field access test
- feat: add struct field access support
Depends on #77.
=> feat: add struct field access support

ibis_substrait/compiler/decompile.py, ibis_substrait/compiler/mapping.py, ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_decompiler.py
xref: ibis-project/tpc-queries#3
=> feat: add ops.Contains -> singular_or_list translation

.github/workflows/ci.yml, ci/release/dry_run.sh, ci/release/verify.sh, dev/lockfile_diff.sh, poetry.lock, shell.nix
=> ci: use dyff instead of git diff for poetry.lock diffing

ibis_substrait/compiler/translate.py, poetry.lock, pyproject.toml
=> fix: remove dev dependencies from core dependencies

poetry.lock, pyproject.toml
=> fix: invalid syntax in pyproject.toml

ibis_substrait/compiler/core.py, ibis_substrait/compiler/translate.py
This PR should fix 
https://github.com/ibis-project/ibis-substrait/issues/384
=> feat: support kwargs in compile 

ibis_substrait/compiler/translate.py
=> feat: add support for ops.FloorDivide

.github/workflows/ci.yml, ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_compiler.py
Fixes #423 
@icexelloss can you try this out on your asof_join extension?
=> fix(emit): check all rel types for existing output mapping

ibis_substrait/compiler/core.py, ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_tpch.py
depends on #501 
keeping this as a draft for the moment, but I didn't want to lose my place.
=> feat(subquery): add support for ExistsSubquery and NotExistsSubquery

.github/workflows/ci.yml
Resolves an upstream issue with some bad path management
=> chore(nix): update cachix/install-nix-action to v20

ibis_substrait/compiler/translate.py
Acero's return type for floor and ceil is float64, so we cast
to ensure that the return type of the data matches the ibis expression
type.
Fixes #410.
=> fix: cast floor and ceil to integer types to workaround acero

ibis_substrait/tests/compiler/test_compiler.py
Test to confirm that we are numbering outputs on the basis of the most recently created columns, not just the parent tables of the child op.
This was broken before because of the intermediate filter operation.
Fixed in #554
=> test: add test for output ordering for agg -> filter -> project

ibis_substrait/tests/integration/test_pyarrow.py
Hey @gforsyth, in https://github.com/apache/arrow/issues/34644 Acero's cast behavior changed and it would be good to have even a basic regression test in ibis-substrait. Prior to the change in the linked issue, this test raised `pyarrow.ArrowInvalid` but no longer does after. I verified this by building different pyarrow versions locally, running the ibis-substrait tests for each version, and verifying the behavior.
=> test: add regression test for recent Acero cast safety change

ibis_substrait/compiler/core.py, ibis_substrait/compiler/mapping.py, ibis_substrait/compiler/translate.py
=> feat: add support for std_dev and variance

ibis_substrait/compiler/mapping.py, ibis_substrait/tests/compiler/test_extensions.py
cc @icexelloss @rtpsw will this do the trick?
Fixes #597
=> fix(uri): allow overriding extension uri when registering extension file

.github/workflows/ci.yml, ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_extensions.py, ibis_substrait/tests/integration/test_pyarrow.py, poetry.lock
=> feat: add support for Ibis 6.x

flake.lock
=> chore(flake): update nixpkgs and poetry2nix

ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_extensions.py
Ibis literals default to Int8, which means users are stuck typing something like `expr.col.round(ibis.literal(2, type="int32'))` which is a pain. Since substrait only allows Int32 for the `digits` arg, we autocast to int32 from any int type
=> feat(autocast): add autocast for digits argument to ops.Round

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/parity_utils.py, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h01/tpc_h01.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h02/tpc_h02.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h03/tpc_h03.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h04/tpc_h04.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h05/tpc_h05.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h06/tpc_h06.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h07/tpc_h07.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h08/tpc_h08.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h09/tpc_h09.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h10/tpc_h10.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h11/tpc_h11.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h12/tpc_h12.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h13/tpc_h13.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h14/tpc_h14.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h15/tpc_h15.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h16/tpc_h16.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h17/tpc_h17.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h18/tpc_h18.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h19/tpc_h19.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h20/tpc_h20.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h21/tpc_h21.json, ibis_substrait/tests/compiler/snapshots/test_tpch/test_compile/tpc_h22/tpc_h22.json, ibis_substrait/tests/compiler/test_parity.py, poetry.lock, pyproject.toml
- adds datafusion to parity tests
- minor changes due to a breaking join type change in substrait
=> feat: add datafusion to parity tests

ibis_substrait/compiler/translate.py, ibis_substrait/tests/compiler/test_parity.py
=> feat: add support for cross join
